config/routes.rb
Rails.application.routes.draw do
  resources :produtos
  resources :posts, only: [:index, :show, :create, :new, :destroy]
  devise_for :users
  root to: "pages#home"
  get "ceo", to: "pages#ceo"
  get "servicos", to: "pages#servicos"
  get "sobre", to: "pages#sobre"
  get "admin", to: "pages#admin"

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/post.rb
class Post < ApplicationRecord
  validates :title, :body, :data, :autor, :img_url, presence: true
  has_one_attached :img_url
end

app/models/produto.rb
class Produto < ApplicationRecord
  validates :nome, :foto, :valor, :desc, :autor, :tipo_produto, presence: true
  has_one_attached :foto
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :home, :ceo, :servicos, :sobre ]

  def home
    @posts = Post.last(9)
    @produtos = Produto.where(tipo_produto: "Curso")
  end

  def ceo
    @posts = Post.last(3)
    @produtos = Produto.where(tipo_produto: "Curso")
  end

  def servicos
  end

  def sobre
  end

  def admin
    if current_user.admin == false
      redirect_to root_path
      flash[:alert] = "Somente Admins podem acessar o painel."
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :index, :show ]

  def index
    @posts = Post.all
  end

  def show
    @post = Post.find(params[:id])
  end

  def new
    @post = Post.new
    if current_user.admin == false
      redirect_to root_path
      flash[:alert] = "Somente Admins podem fazer criação de novos posts."
    end
  end

  def create
    @post = Post.new(post_params)
    agora = Time.now
    @post.data = agora.strftime("%d/%m/%Y - %H:%M:%S")
    if @post.save
      redirect_to post_path(@post)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to posts_path
  end

  private

  def post_params
    params.require(:post).permit(:title, :body, :img_url, :data, :autor)
  end
end

app/controllers/produtos_controller.rb
class ProdutosController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :index, :show ]

  def index
    @produtos = Produto.all
  end

  def show
    @produtos = Produto.last(3)
    @produto = Produto.find(params[:id])
  end

  def new
    @produto = Produto.new
    if current_user.admin == false
      redirect_to root_path
      flash[:alert] = "Somente Admins podem fazer criação de novos produtos."
    end
  end

  def create
    @produto = Produto.new(produto_params)
    if @produto.save
      redirect_to produto_path(@produto)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @produto = Produto.find(params[:id])
  end

  def update
    @produto = Produto.find(params[:id])
    if @produto.update(produto_params)
      redirect_to produto_path(@produto)
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @produto = Produto.find(params[:id])
    @produto.destroy
    redirect_to produtos_path
  end

  private

  def produto_params
    params.require(:produto).permit(:tipo_produto, :tipo_curso, :foto, :nome, :valor, :modulos, :autor, :desc)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/pages/admin.html.erb
<section class="margin-top-form container text-center">
  <h4><%= link_to "Criar Post", new_post_path, class: "btn btn-secondary btn-lg" %></h4>
  <h4><%= link_to "Criar Produto", new_produto_path, class: "btn btn-secondary btn-lg" %></h4>
</section>

app/views/pages/servicos.html.erb
<style>
  .main-menu .navbar-collapse li a {
    color: #fff;
  }
</style>
<!-- Page Banner Start -->
<section
        class="page-banner-area rel z-1 text-white text-center"
        style="background-image: linear-gradient(rgba(0,0,0,0.4), rgba(0,0,0,0.9)), url(<%= image_path 'banner-servico.jpg', alt:'banner' %>)"
      >
  <div class="container">
    <div class="banner-inner rpt-10">
      <h2 class="page-title wow fadeInUp delay-0-2s">Serviços</h2>
      <nav aria-label="breadcrumb">
        <ol class="breadcrumb wow fadeInUp delay-0-4s">
          <li class="breadcrumb-item"><a href="/">home</a></li>
          <li class="breadcrumb-item active">Serviços</li>
        </ol>
      </nav>
    </div>
  </div>
  <%= image_tag "shapes/circle-one.png", alt:"circle", class: "circle-one" %>
  <%= image_tag "shapes/circle-two.png", alt:"circle", class: "circle-two" %>
</section>
<!-- Page Banner End -->
<!-- Instructors Section Start -->
<section class="instructors-page pt-130 rpt-100 pb-70 rpb-40">
  <div class="container">
    <div class="row justify-content-center">
      <div class="col-lg-3 col-md-4 col-sm-6">
        <div class="instructor-item wow fadeInUp delay-0-2s">
          <div class="image">
            <%= image_tag "teams/team1.jpg", alt:"Produto" %>
          </div>
          <div class="member-description">
            <h4>Combate Contra as Drogas</h4>
            <span>Cursos, Livros e Acompanhamento Pessoal</span> <br>
            <%= link_to "Ver Loja", produtos_path, class: "social-style-two ver-loja" %>
          </div>
        </div>
      </div>
      <div class="col-lg-3 col-md-4 col-sm-6">
        <div class="instructor-item wow fadeInUp delay-0-4s">
          <div class="image">
            <%= image_tag "teams/team2.jpg", alt:"Produto" %>
          </div>
          <div class="member-description">
            <h4>Coaching Pessoal</h4>
            <span>Acompanhamento Online ou Presencial</span> <br>
            <%= link_to "Ver Loja", produtos_path, class: "social-style-two ver-loja" %>
          </div>
        </div>
      </div>
      <div class="col-lg-3 col-md-4 col-sm-6">
        <div class="instructor-item wow fadeInUp delay-0-6s">
          <div class="image">
            <%= image_tag "teams/team3.jpg", alt:"Produto" %>
          </div>
          <div class="member-description">
            <h4>Palestras</h4>
            <span>Palestras Sobre Diversos Temas</span>
            <br>
            <%= link_to "Ver Loja", produtos_path, class: "social-style-two ver-loja" %>
          </div>
        </div>
      </div>
      <div class="col-lg-3 col-md-4 col-sm-6">
        <div class="instructor-item wow fadeInUp delay-0-8s">
          <div class="image">
            <%= image_tag "teams/team4.jpg", alt:"Produto" %>
          </div>
          <div class="member-description">
            <h4>Treinamentos</h4>
            <span
                    >Treinamentos para Concursos Públicos, Enem e
              Vestibulares</span
                  >
            <br>
            <%= link_to "Ver Loja", produtos_path, class: "social-style-two ver-loja" %>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>
<!-- Instructors Section End -->
<script>
  document.querySelectorAll(".navbar-collapse.collapse.clearfix .navigation.clearfix>li").forEach((element) => {
    if(element.innerText.toUpperCase() === "SERVIÇOS") {
      element.classList.add("current")
    } else {
      element.classList.remove("current")
    }
  });
</script>

app/views/posts/index.html.erb
<style>
  .main-menu .navbar-collapse li a {
    color: #fff;
  }
</style>
<!-- Page Banner Start -->
<section
        class="page-banner-area rel z-1 text-white text-center"
        style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.9)), url(<%= image_path "banner-blog.jpg" %>)"
      >
  <div class="container">
    <div class="banner-inner rpt-10">
      <h2 class="page-title wow fadeInUp delay-0-2s">Nosso Blog</h2>
      <nav aria-label="breadcrumb">
        <ol class="breadcrumb wow fadeInUp delay-0-4s">
          <li class="breadcrumb-item"><a href="/">home</a></li>
          <li class="breadcrumb-item active">Nosso Blog</li>
        </ol>
      </nav>
    </div>
  </div>
  <%= image_tag "shapes/circle-one.png", alt:"Circle", class: "circle-one" %>
  <%= image_tag "shapes/circle-two.png", alt:"Circle", class: "circle-two" %>
</section>
<!-- Page Banner End -->
<!-- Blog Standard Start -->
<section class="blog-standard-area py-130 rpt-95 rpb-100">
  <div class="container">
    <div class="row justify-content-center">
      <div class="col-lg-10">
        <div class="blog-standard-wrap">
          <% if @posts %>
            <% if @posts.size != 0 %>
              <% @posts.each do |post| %>
                <div class="blog-standard-item wow fadeInUp delay-0-2s">
                  <div class="image">
                    <%= cl_image_tag post.img_url.key, height: 450, width: 720, style: "object-fit: cover;", alt: "imagem produto" %>
                  </div>
                  <div class="blog-standard-content">
                    <div class="content">
                      <ul class="blog-standard-header">
                        <li><span class="name"><%= post.autor %></span></li>
                        <li>
                          <i class="far fa-calendar-alt"></i>
                          <%= link_to post.data, post_path(post) %>
                        </li>
                      </ul>
                      <h3>
                        <%= link_to post.title, post_path(post) %>
                      </h3>
                      <p class="descricao-post">
                        <%= post.body.split(/\\n/).join("<br />").html_safe %>
                      </p>
                      <%= link_to "Ver Mais <i class='fas fa-arrow-right'></i>".html_safe, post_path(post), class: "theme-btn style-two" %>
                    </div>
                  </div>
                </div>
              <% end %>
            <% else %>
              <h2 class="container text-center">Sem Posts</h2>
            <% end %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</section>
<!-- Blog Standard End -->
<script>
  document.querySelectorAll(".navbar-collapse.collapse.clearfix .navigation.clearfix>li").forEach((element) => {
    if(element.innerText.toUpperCase() === "BLOG") {
      element.classList.add("current")
    } else {
      element.classList.remove("current")
    }
  });
</script>

app/views/posts/new.html.erb
<section class="container text-center p-5 margin-top-form form-login">
  <div class="container mt-5">
    <%= simple_form_for(@post) do |f| %>
      <%= f.input :title, placeholder: "Digite o Título do post", label: "Título" %>
      <%= f.input :body, placeholder: "Texto", label: "Digite o corpo do texto", as: :text, :input_html => {:rows => 8 } %>
      **Para pular linhas no corpo do texto, adicione \n
      <%= f.input :autor, placeholder: "Digite o Autor do post", label: "Autor" %>
      <br>
      <br>
      <%= f.input :img_url, as: :file, label: "Imagem" %>
      <%= f.submit "Criar post", class: "botao-submit" %>
    <% end %>
  </div>
</section>
<script>
  document.querySelectorAll(".navbar-collapse.collapse.clearfix .navigation.clearfix>li").forEach((element) => {
    if(element.innerText.toUpperCase() === "BLOG") {
      element.classList.add("current")
    } else {
      element.classList.remove("current")
    }
  });
</script>

app/views/posts/show.html.erb
<!-- Blog Details Start -->
<section class="blog-details-area py-130 rpy-100">
  <div class="container">
    <div class="row justify-content-center">
      <div class="col-lg-10">
        <%= link_to "<i class='fas fa-arrow-left'></i> Retornar ao Blog".html_safe, posts_path, class: "mb-5 pb-5" %>
        <div class="blog-details-wrap">
          <div class="image mb-25 wow fadeInUp delay-0-2s">
            <%= cl_image_tag @post.img_url.key, height: 450, width: 720, style: "object-fit: cover;", alt: "imagem post" %>
          </div>
          <ul class="blog-standard-header wow fadeInUp delay-0-2s">
            <li><span class="name"><%= @post.autor %></span></li>
            <li>
              <i class="far fa-calendar-alt"></i>
              <%= @post.data %>
            </li>
            <li>
              <% if current_user %>
                <% if current_user.admin == true %>
                  <%= link_to "Excluir Post", post_path(@post), data: {turbo_method: :delete, turbo_confirm: "Você tem certeza que deseja excluir este Post? Essa ação não pode ser desfeita!"}, class: "excluir" %>
                <% end %>
              <% end %>
            </li>
          </ul>
          <h3 class="title"><%= @post.title %></h3>
          <p class="post-text">
            <%= @post.body.split(/\\n/).join("<br />").html_safe %>
          </p>
          <%= link_to "<i class='fas fa-arrow-left'></i> Retornar ao Blog".html_safe, posts_path, class: "me-5" %>
        </div>
      </div>
    </div>
  </div>
</section>
<!-- Blog Details End -->
<!-- <section class="container text-center mt-3">
<h1>
  <%= @post.title %>
</h1>
<%= cl_image_tag @post.img_url.key, height: 300, width: 400, crop: :fill %>
<br>
<p id="texto-blog"><span class="ms-3"></span><%= @post.body.split(/\\n/).join("<br />").html_safe %></p>
<br>
<br>
<%= @post.data %>
<br>
<% if current_user %>
  <% if current_user.admin == true %>
    <%= link_to "Excluir Post",
    post_path(@post),
    data: {turbo_method: :delete, turbo_confirm: "Você tem certeza que deseja excluir este Post? Essa ação não pode ser desfeita!"}
  %>
  <% end %>
<% end %>
<%= link_to "Posts", posts_path %>
</section>
-->
<script>
  document.querySelectorAll(".navbar-collapse.collapse.clearfix .navigation.clearfix>li").forEach((element) => {
    if(element.innerText.toUpperCase() === "BLOG") {
      element.classList.add("current")
    } else {
      element.classList.remove("current")
    }
  });
</script>

app/views/produtos/edit.html.erb
<style>
  select {
    display: none !important;
  }
</style>
<section class="container text-center p-5 margin-top-form form-login">
  <div class="container mt-5">
    <%= simple_form_for(@produto) do |f| %>
      <%= f.input :nome, placeholder: "Digite o Nome do Produto", label: "Produto" %>
      <%= f.input :desc, placeholder: "Descrição do Produto", label: "Digite a descrição do produto", :input_html => {:rows => 8 } %>
      **Para pular linhas no corpo do texto, adicione \n
      <%= f.input :valor, label: "Valor do Produto" %>
      <%= f.input :autor, label: "Responsável" %>
      <%= f.input :foto, as: :file, label: "Imagem do Produto" %>
      <%= f.input :tipo_produto, label: "Tipo do Produto", as: :select, collection: {"Curso" => "Curso", "Ebook" => "Ebook", "Livro" => "Livro", "Desintoxicação" => "Desintoxicação", "Palestra" => "Palestra", "Outro" => "Outro"} %>
      <%= f.input :tipo_curso, label: "Tipo do curso", as: :select, collection: {"Combate contra as Drogas" => "Combate contra as Drogas", "Memorização" => "Memorização", "Concentração" => "Concentração", "Super Leitura" => "Super Leitura", "Outro" => "Outro"} %>
      <%= f.input :modulos, label: "Quantidade de módulos", as: :numeric %>
      <%= f.submit "Criar post", class: "botao-submit" %>
    <% end %>
  </div>
</section>
<script>
  document.querySelectorAll(".navbar-collapse.collapse.clearfix .navigation.clearfix>li").forEach((element) => {
    if(element.innerText.toUpperCase() === "LOJA") {
      element.classList.add("current")
    } else {
      element.classList.remove("current")
    }
  });
</script>

app/views/produtos/new.html.erb
<style>
  select {
    display: none !important;
  }
</style>
<section class="container text-center p-5 margin-top-form form-login">
  <div class="container mt-5">
    <%= simple_form_for(@produto) do |f| %>
      <%= f.input :nome, placeholder: "Digite o Nome do Produto", label: "Produto" %>
      <%= f.input :desc, placeholder: "Descrição do Produto", label: "Digite a descrição do produto", :input_html => {:rows => 8 } %>
      **Para pular linhas no corpo do texto, adicione \n
      <%= f.input :valor, label: "Valor do Produto" %>
      <%= f.input :autor, label: "Responsável" %>
      <%= f.input :foto, as: :file, label: "Imagem do Produto" %>
      <%= f.input :tipo_produto, label: "Tipo do Produto", as: :select, collection: {"Curso" => "Curso", "Ebook" => "Ebook", "Livro" => "Livro", "Desintoxicação" => "Desintoxicação", "Palestra" => "Palestra", "Outro" => "Outro"} %>
      <%= f.input :tipo_curso, label: "Tipo do curso", as: :select, collection: {"Combate contra as Drogas" => "Combate contra as Drogas", "Memorização" => "Memorização", "Concentração" => "Concentração", "Super Leitura" => "Super Leitura", "Outro" => "Outro"} %>
      <%= f.input :modulos, label: "Quantidade de módulos", as: :numeric %>
      <%= f.submit "Criar Produto", class: "botao-submit" %>
    <% end %>
  </div>
</section>
<script>
  document.querySelectorAll(".navbar-collapse.collapse.clearfix .navigation.clearfix>li").forEach((element) => {
    if(element.innerText.toUpperCase() === "LOJA") {
      element.classList.add("current")
    } else {
      element.classList.remove("current")
    }
  });
</script>

app/views/produtos/show.html.erb
<!-- Product Details Start -->
<section class="product-details pt-130 rpt-100">
  <div class="container">
    <div class="row align-items-center justify-content-between">
      <div class="col-lg-6">
        <div
                class="product-details-images rmb-55 wow fadeInLeft delay-0-2s"
              >
          <div class="tab-content preview-images">
            <div
                    class="tab-pane fade preview-item active show"
                    id="preview1"
                  >
              <%= cl_image_tag @produto.foto.key, height: 430, width: 450, style: "object-fit: cover;", alt: "imagem produto" %>
            </div>
          </div>
        </div>
      </div>
      <div class="col-lg-5">
        <div class="product-details-content wow fadeInRight delay-0-2s">
          <%= link_to "<i class='fas fa-arrow-left'></i> Todos os Produtos".html_safe, produtos_path, class: "me-3" %>
          <% if current_user %>
            <% if current_user.admin == true %>
              <%= link_to "<i class='fas fa-pencil'></i>Editar Produto".html_safe, edit_produto_path(@produto), class: "me-3 editar" %>
              <%= link_to "<i class='fas fa-trash'></i>Excluir produto".html_safe, produto_path(@produto), data: {turbo_method: :delete, turbo_confirm: "Você tem certeza que deseja excluir este produto? Essa ação não pode ser desfeita!"}, class: "excluir" %>
            <% end %>
          <% end %>
          <h2 class="nome-produto"><%= @produto.nome %></h2>
          <div class="author">
            <h6><%= @produto.autor %></h6>
          </div>
          <div class="ratting-price mb-20">
            <span class="price valor-produto"><%= @produto.valor %></span>
          </div>
          <ul class="category-tags pt-10 pb-5">
            <li>
              <b>Categoria</b>
              <span>:</span>
              <%= @produto.tipo_produto %>
            </li>
            <% if @produto.tipo_produto == "Palestra" || @produto.tipo_produto == "Curso" %>
              <li>
                <b>Tema</b>
                <span>:</span>
                <%= @produto.tipo_curso %>
              </li>
              <% if @produto.tipo_produto == "Curso" %>
                <li>
                  <b>Módulos</b>
                  <span>:</span>
                  <%= @produto.modulos %>
                </li>
              <% end %>
            <% end %>
          </ul>
          <hr />
          <form action="#" class="add-to-cart mt-95 rmt-45">
            <input type="number" value="1" min="1" max="20" required class="quantidade" />
            <button type="submit" class="theme-btn style-two comprar">
              Comprar
            </button>
          </form>
        </div>
      </div>
    </div>
    <ul class="nav nav-tabs product-information-tab pt-55 mb-40">
      <li>
        <a href="#details" data-toggle="tab" class="active show"
                >Descrição</a
              >
      </li>
    </ul>
    <div class="tab-content wow fadeInUp delay-0-2s">
      <div class="tab-pane active show" id="details">
        <p><%= @produto.desc.split(/\\n/).join("<br />").html_safe %></p>
      </div>
    </div>
  </div>
</section>
<!-- Product Details End -->
<!-- Popular Products Start -->
<section class="popular-product pt-90 rpt-60 pb-100 rpb-70">
  <div class="container">
    <div class="section-title text-center mb-45">
      <span class="sub-title-two">Outros Produtos</span>
      <h2>Confira Nossos Novos Produtos</h2>
    </div>
    <div class="row justify-content-center">
      <% @produtos.each do |produto| %>
        <div class="col-xl-3 col-lg-4 col-sm-6">
          <div class="product-item wow fadeInUp delay-0-4s">
            <div class="product-image">
              <%= cl_image_tag produto.foto.key, height: 265, width: 260, style: "object-fit: cover;", alt: "imagem produto" %>
              <a href="#" class="cart-btn botao-comprar-todos">Comprar</a>
            </div>
            <div class="product-content">
              <h6><%= link_to produto.nome, produto_path(produto) %></h6>
              <span class="category"><%= produto.tipo_produto %></span>
              <br>
              <span class="price"><span><%= produto.valor %></span></span>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</section>
<!-- Popular Products End -->
<!-- <section class="container text-center mt-3">
  <h1>
    <%= @produto.nome %>
  </h1>
  <%= cl_image_tag @produto.foto.key, height: 300, width: 400, crop: :fill %>
  <br>
  <p id="texto-produto"><span class="ms-3"></span><%= @produto.desc.split(/\\n/).join("<br />").html_safe %></p>
  <br>
  <br>
  <%= @produto.valor %>
  <br>
  <% if current_user %>
    <% if current_user.admin == true %>
      <%= link_to "Excluir produto",
    produto_path(@produto),
    data: {turbo_method: :delete, turbo_confirm: "Você tem certeza que deseja excluir este produto? Essa ação não pode ser desfeita!"}
  %>
    <% end %>
  <% end %>
  <%= link_to "Produtos", produtos_path %>
</section> -->
<script>
  document.querySelectorAll(".navbar-collapse.collapse.clearfix .navigation.clearfix>li").forEach((element) => {
    if(element.innerText.toUpperCase() === "LOJA") {
      element.classList.add("current")
    } else {
      element.classList.remove("current")
    }
  });
</script>
<script>
  let botaoComprar = document.querySelector(".comprar")
  let nomeProduto = document.querySelector(".nome-produto").innerText
  let valorProduto = parseInt(document.querySelector(".valor-produto").innerText)

  botaoComprar.addEventListener("click", function() {
    let quantidade = parseInt(document.querySelector(".quantidade").value)
    event.preventDefault()
    window.open(`https://wa.me/5538991280123?text=*COMPRAR%20PRODUTO*%0A
    *PRODUTO:*%20${nomeProduto}%0A
    *VALOR%20DO%20PRODUTO:*%20R$${valorProduto}%0A
    *QUANTIDADE:*%20${quantidade}%0A
    ---------------------------------%0A
    *TOTAL:*%20R$${quantidade * valorProduto}`)
  })
</script>
<script>
  let botoesComprar = document.querySelectorAll(".botao-comprar-todos")
  botoesComprar.forEach((botao) => {
    botao.addEventListener("click", function() {
      window.open(`https://wa.me/5538991280123?text=*COMPRAR%20PRODUTO*%0A
      *PRODUTO:*%20${botao.parentElement.parentElement.children[1].children[0].innerText}%0A
      *VALOR%20DO%20PRODUTO:*%20R$${botao.parentElement.parentElement.children[1].children[3].innerText}%0A
      *QUANTIDADE:*%20${1}%0A
      ---------------------------------%0A
      *TOTAL:*%20R$${1 * parseInt(botao.parentElement.parentElement.children[1].children[3].innerText)}`)
    })
  });
</script>

app/views/shared/_footer.html.erb
<!-- Footer Area Start -->
<footer class="main-footer bg-blue text-white pt-75">
  <div class="container">
    <div class="row justify-content-between">
      <div class="col-lg-3 col-sm-4">
        <div class="footer-widget about-widget">
          <h5 class="footer-title">Sobre Nós</h5>
          <p>
            Nossas palestras, cursos, oficinas e/ou intervenções teatrais são verdadeiros shows de motivação pessoal e profissional
          </p>
          <h5 class="pt-5">Redes Sociais</h5>
          <div class="social-style-one">
            <a href="#"><i class="fab fa-whatsapp"></i></a>
            <a href="#"><i class="fab fa-facebook-f"></i></a>
            <a href="#"><i class="fab fa-instagram"></i></a>
          </div>
        </div>
      </div>
      <div class="col-lg-2 col-md-3 col-sm-4">
        <div class="footer-widget menu-widget">
          <h5 class="footer-title">Links</h5>
          <ul>
            <li><a href="/">Home</a></li>
            <li><%= link_to "Serviços", servicos_path %></li>
            <li><%= link_to "Sobre", sobre_path %></li>
            <li><%= link_to "CEO", ceo_path %></li>
            <li><%= link_to "Blog", posts_path %></li>
            <li><%= link_to "Loja", produtos_path %></li>
          </ul>
        </div>
      </div>
      <div class="col-lg-5">
        <div class="row">
          <div class="col-sm-6">
            <div class="footer-widget contact-info-widget">
              <h5 class="footer-title">Entrar em Contato</h5>
              <ul>
                <li>
                  <i class="fas fa-map-marker-alt"></i> Rua São Pedro, 709
                  - Todos Os Santos, Montes Claros - MG
                </li>
                <li>
                  <i class="far fa-envelope"></i>
                  <a href="mailto:pratikartes@gmail.com"
                          >pratikartes@gmail.com</a
                        >
                </li>
                <li>
                  <i class="fab fa-whatsapp"></i>
                  <a href="#">(38) 98834-9144</a>
                </li>
                <li>
                  <i class="fab fa-whatsapp"></i> <a href="#">(38) 99186-2918</a>
                </li>
              </ul>
            </div>
          </div>
          <div class="col-sm-6">
            <div class="footer-widget video-widget">
              <p>Conheça a Pratikartes e seu CEO</p>
              <div class="video-widget overlay my-20">
                <%= image_tag "footer/video.jpg", alt:"Video" %>
                <a
                        href="https://www.youtube.com/watch?v=9Y7ma241N8k"
                        class="mfp-iframe video-play"
                        ><i class="fas fa-play"></i
                      ></a>
              </div>
              <%= link_to "Ver Mais <i class='fas fa-arrow-right'></i>".html_safe, sobre_path, class: "read-more" %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="copyright-area bg-dark-blue rel">
    <div class="container">
      <div class="copyright-inner">
        <p>
          © 2023.
          <a href="https://www.fswebsite.net" target="_blank">FSWeb</a> |
          Todos os Direitos Reservados.
        </p>
        <ul class="footer-menu">
          <li><%= link_to "Serviços", servicos_path %></li>
          <li><%= link_to "A Empresa", sobre_path %></li>
          <li><%= link_to "Enviar Mensagem", "#" %></li>
        </ul>
      </div>
    </div>
    <!-- Scroll Top Button -->
    <button class="scroll-top scroll-to-target" data-target="html">
      <span class="fas fa-angle-double-up"></span>
    </button>
    <div class="container text-center">
      <%= link_to "<i class='fas fa-cog'></i>".html_safe, admin_path %>
    </div>
  </div>
</footer>
<!-- Footer Area End -->